language: python
dist: bionic
git:
  clone: true
  autocrlf: true
virtualenv:
  system_site_packages: true
install:
  - pip install -r requirements.txt
script: flake8
after_success:
  - coveralls
#jobs:
#  include:
#    - stage: "Test"
#      name: "Unit Tests"
#      script: echo "Running unit tests..."
#      script: *******
#    - name: "Integration Tests"
#      script: echo "Running integration tests..."
#      script: ********
